---
title: "Anaemia in pregnancy in Ghana in 2023"
author: "Shih Ting Tsemg"
date: "`r format(Sys.time(), format = "%d %B %Y %H:%M")`"
output:
  word_document:
    toc: true
    toc_depth: '3'
  html_document:
    toc: true
    toc_depth: 3
    code_download: true
subtitle: Data analysis
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  error = FALSE,
  echo = FALSE
)

suppressPackageStartupMessages(source(here::here("packages.R")))
anc_data_processed07 <- read_csv("data/anc_data_processed07.csv")
for (f in list.files(here::here("R"), full.names = TRUE)) source (f)



targets::tar_load(c(anc_data_raw, anc_data_raw_metadata, anc_data_processed,  anc_data_processed07,anc_data_processed_metadata,anc_data_processed_subset_2023))

```


## Description of the sample

```{r sample-description}

# Table of age groups ----
age_group_tab <- anc_data_processed_subset_2023 %>%
  dplyr::count(age_group) %>%
  dplyr::arrange(desc(n)) %>%
  dplyr::mutate(prop = n / unique(anc_data_processed_subset_2023$total_n)) %>%
  dplyr::rename(var = age_group)

## NOTE: Good to make a population pyramid or bar plot for age groups to show
## distribution

# Table of professions ----
profession_tab <- anc_data_processed_subset_2023 %>%
  dplyr::count(profession) %>%
  dplyr::arrange(desc(n)) %>%
  dplyr::mutate(prop = n / unique(anc_data_processed_subset_2023$total_n)) %>%
  dplyr::rename(var = profession)


# Table of detail professions group ----
profession_group_tab <- anc_data_processed_subset_2023 %>%
  dplyr::count(profession_summary) %>%
  dplyr::arrange(desc(n)) %>%
  dplyr::mutate(prop = n / unique(anc_data_processed_subset_2023$total_n)) %>%
  dplyr::rename(var = profession_summary)
  
# Education Level ---
education_summary_tab <- anc_data_processed_subset_2023 %>%
  dplyr::count(education_level_summary) %>%
  dplyr::arrange(desc(n)) %>%
  dplyr::mutate(prop = n / unique(anc_data_processed_subset_2023$total_n)) %>%
  dplyr::rename(var = education_level_summary)

# Education Level ---
education_tab <- anc_data_processed_subset_2023 %>%
  dplyr::count(education_level) %>%
  dplyr::arrange(desc(n)) %>%
  dplyr::mutate(prop = n / unique(anc_data_processed_subset_2023$total_n)) %>%
  dplyr::rename(var = education_level)

# Marital status ----
marital_tab <- anc_data_processed_subset_2023 %>%
  dplyr::count(marital_status) %>%
  dplyr::arrange(desc(n)) %>%
  dplyr::mutate(prop = n / unique(anc_data_processed_subset_2023$total_n)) %>%
  dplyr::rename(var = marital_status)

# Location/neighbourhood ---
address_tab <- anc_data_processed_subset_2023 %>%
  dplyr::count(address) %>%
  dplyr::arrange(desc(n)) %>%
  dplyr::mutate(prop = n / unique(anc_data_processed_subset_2023$total_n)) %>%
  dplyr::rename(var = address)

# Sickle cell status ----
sickle_tab <- anc_data_processed_subset_2023 %>%
  dplyr::count(sickle_cell) %>%
  dplyr::arrange(desc(n)) %>%
  dplyr::mutate(prop = n / unique(anc_data_processed_subset_2023$total_n)) %>%
  dplyr::rename(var = sickle_cell)

# Malaria ----
malaria_tab <- anc_data_processed_subset_2023 %>%
  dplyr::count(malaria) %>%
  dplyr::arrange(desc(n)) %>%
  dplyr::mutate(prop = n / unique(anc_data_processed_subset_2023$total_n)) %>%
  dplyr::rename(var = malaria)

# Create overall summary table ----
median_age_tab <- anc_data_processed_subset_2023 %>%
  dplyr::summarise(
    var = "median_age",
    median_age = median(age, na.rm = TRUE)
  )

# Create overall table ----
knitr::kable(
  x = median_age_tab,
  col.names = c("Variable", "Value")
) |>
  kableExtra::kable_paper()


knitr::kable(
  x = rbind(
    age_group_tab,
    education_tab,
    profession_tab,
    address_tab,
    marital_tab,
    sickle_tab,
    malaria_tab
  ),
  col.names = c("Variable", "n", "%")
) |>
  kableExtra::kable_paper()

```


## Outcome variable and bivariate analysis

```{r histogram of age group}
#histogram of age group
anc_data_processed_subset_2023 %>%
  dplyr::count(anaemia_status)
anc_data_processed_subset_2023 %>%
  dplyr::count(anaemia_status, age_group) %>%
  dplyr::arrange(desc(n)) %>%
  ggplot(aes(x = age_group, y = n)) +
  geom_col() +
  facet_wrap(. ~ anaemia_status, ncol = 3)

#histogram of education level
anc_data_processed_subset_2023 %>%
  dplyr::count(anaemia_status)
anc_data_processed_subset_2023 %>%
  dplyr::count(anaemia_status, education_level) %>%
  dplyr::arrange(desc(n)) %>%
  ggplot(aes(x = education_level, y = n)) +
  geom_col() +
  facet_wrap(. ~ anaemia_status, ncol = 3)

#histogram of education level group
anc_data_processed_subset_2023 %>%
  dplyr::count(anaemia_status)
anc_data_processed_subset_2023 %>%
  dplyr::count(anaemia_status, education_level_summary) %>%
  dplyr::arrange(desc(n)) %>%
  ggplot(aes(x = education_level_summary, y = n)) +
  geom_col() +
  facet_wrap(. ~ anaemia_status, ncol = 3)

#histogram of profession
anc_data_processed_subset_2023 %>%
  dplyr::count(anaemia_status)
anc_data_processed_subset_2023 %>%
  dplyr::count(anaemia_status, profession) %>%
  dplyr::arrange(desc(n)) %>%
  ggplot(aes(x = profession, y = n)) +
  geom_col() +
  facet_wrap(. ~ anaemia_status, ncol = 3)


#histogram of detail profession group
anc_data_processed_subset_2023 %>%
  dplyr::count(anaemia_status)
anc_data_processed_subset_2023 %>%
  dplyr::count(anaemia_status, profession_summary) %>%
  dplyr::arrange(desc(n)) %>%
  ggplot(aes(x = profession_summary, y = n)) +
  geom_col() +
  facet_wrap(. ~ anaemia_status, ncol = 3)

#marital status
anc_data_processed_subset_2023 %>%
  dplyr::count(anaemia_status)
anc_data_processed_subset_2023 %>%
  dplyr::count(anaemia_status, marital_status) %>%
  dplyr::arrange(desc(n)) %>%
  ggplot(aes(x = marital_status, y = n)) +
  geom_col() +
  facet_wrap(. ~ anaemia_status, ncol = 3)
#sickle cell
anc_data_processed_subset_2023 %>%
  dplyr::count(anaemia_status)
anc_data_processed_subset_2023 %>%
  dplyr::count(anaemia_status, sickle_cell) %>%
  dplyr::arrange(desc(n)) %>%
  ggplot(aes(x = sickle_cell, y = n)) +
  geom_col() +
  facet_wrap(. ~ anaemia_status, ncol = 3)
#malaria
anc_data_processed_subset_2023 %>%
  dplyr::count(anaemia_status)
anc_data_processed_subset_2023 %>%
  dplyr::count(anaemia_status, malaria) %>%
  dplyr::arrange(desc(n)) %>%
  ggplot(aes(x = malaria, y = n)) +
  geom_col() +
  facet_wrap(. ~ anaemia_status, ncol = 3)


```


## Description of the sample

### 2023 Summary statistics table

```{r bivariable description}
# anaemia status and age group
anaemia_age_group_2023 <- anc_data_processed_subset_2023 %>%
  group_by(anaemia_status, age_group) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  group_by(anaemia_status) %>%
  mutate(percent = count / sum(count) * 100) %>%
  ungroup()
# long
anaemia_age_group_2023_long <- anaemia_age_group_2023  %>%
  pivot_longer(cols = c(count, percent), names_to = "measure", values_to = "value")

age_group_2023_table <- anaemia_age_group_2023_long  %>%
  pivot_wider(names_from = c(anaemia_status, measure), values_from = value)

# Render the table in R Markdown
knitr::kable(
  age_group_2023_table,
  format = "html",
  col.names = c("Age Group", "Anaemic Count", "Anaemic Percent", "Non Anaemic Count", "Non Anaemic Percent","None value count", "None value Percent")
) %>%
  kableExtra::kable_paper()
write_xlsx(age_group_2023_table)

# anaemia status and education 
anaemia_education_2023 <- anc_data_processed_subset_2023 %>%
  group_by(anaemia_status, education_level) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  group_by(anaemia_status) %>%
  mutate(percent = count / sum(count) * 100) %>%
  ungroup()


anaemia_education_2023_long <- anaemia_education_2023  %>%
  pivot_longer(cols = c(count, percent), names_to = "measure", values_to = "value")

education_2023_table <- anaemia_education_2023_long  %>%
  pivot_wider(names_from = c(anaemia_status, measure), values_from = value)
knitr::kable(
  education_2023_table,
  format = "html",
  col.names = c("Education Level", "Anaemic Count", "Anaemic Percent", "Non Anaemic Count", "Non Anaemic Percent","None value count", "None value Percent")
) %>%
  kableExtra::kable_paper()

anaemia_profession_group_2023 <- anc_data_processed_subset_2023 %>%
  group_by(anaemia_status, profession_summary) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  group_by(anaemia_status) %>%
  mutate(percent = count / sum(count) * 100) %>%
  ungroup()
# long
anaemia_profession_group_2023_long <- anaemia_profession_group_2023  %>%
  pivot_longer(cols = c(count, percent), names_to = "measure", values_to = "value")

profession_group_2023_table <- anaemia_profession_group_2023_long  %>%
  pivot_wider(names_from = c(anaemia_status, measure), values_from = value)
knitr::kable(
  profession_group_2023_table,
  format = "html",
  col.names = c("Profession Group", "Anaemic Count", "Anaemic Percent", "Non Anaemic Count", "Non Anaemic Percent","None value count", "None value Percent")
) %>%
  kableExtra::kable_paper()



# anaemia status and profession group
anaemia_profession_group_2023 <- anc_data_processed_subset_2023 %>%
  group_by(anaemia_status, profession_summary) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  group_by(anaemia_status) %>%
  mutate(percent = count / sum(count) * 100) %>%
  ungroup()
# long
anaemia_profession_group_2023_long <- anaemia_profession_group_2023  %>%
  pivot_longer(cols = c(count, percent), names_to = "measure", values_to = "value")

profession_group_2023_table <- anaemia_profession_group_2023_long  %>%
  pivot_wider(names_from = c(anaemia_status, measure), values_from = value)
knitr::kable(
  profession_group_2023_table,
  format = "html",
  col.names = c("Profession Group", "Anaemic Count", "Anaemic Percent", "Non Anaemic Count", "Non Anaemic Percent","None value count", "None value Percent")
) %>%
  kableExtra::kable_paper()


# anaemia status and location
anaemia_location_2023 <- anc_data_processed_subset_2023 %>%
  group_by(anaemia_status, address) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  group_by(anaemia_status) %>%
  mutate(percent = count / sum(count) * 100) %>%
  ungroup()
# long
anaemia_location_2023_long <- anaemia_location_2023  %>%
  pivot_longer(cols = c(count, percent), names_to = "measure", values_to = "value")

location_2023_table <- anaemia_location_2023_long  %>%
  pivot_wider(names_from = c(anaemia_status, measure), values_from = value)

knitr::kable(
  location_2023_table,
  format = "html",
  col.names = c("Location", "Anaemic Count", "Anaemic Percent", "Non Anaemic Count", "Non Anaemic Percent","None value count", "None value Percent")
) %>%
  kableExtra::kable_paper()



# anaemia status and marital group
anaemia_marital_2023 <- anc_data_processed_subset_2023 %>%
  group_by(anaemia_status, marital_status) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  group_by(anaemia_status) %>%
  mutate(percent = count / sum(count) * 100) %>%
  ungroup()
# long
anaemia_marital_2023_long <- anaemia_marital_2023  %>%
  pivot_longer(cols = c(count, percent), names_to = "measure", values_to = "value")

marital_2023_table <- anaemia_marital_2023_long  %>%
  pivot_wider(names_from = c(anaemia_status, measure), values_from = value)

knitr::kable(
  marital_2023_table,
  format = "html",
  col.names = c("Marital status", "Anaemic Count", "Anaemic Percent", "Non Anaemic Count", "Non Anaemic Percent","None value count", "None value Percent")
) %>%
  kableExtra::kable_paper()


# anaemia status and sickle cell
anaemia_sicklecell_2023 <- anc_data_processed_subset_2023 %>%
  group_by(anaemia_status, sickle_cell) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  group_by(anaemia_status) %>%
  mutate(percent = count / sum(count) * 100) %>%
  ungroup()
# long
anaemia_sicklecell_2023_long <- anaemia_sicklecell_2023  %>%
  pivot_longer(cols = c(count, percent), names_to = "measure", values_to = "value")

sicklecell_2023_table <- anaemia_sicklecell_2023_long  %>%
  pivot_wider(names_from = c(anaemia_status, measure), values_from = value)

knitr::kable(
  sicklecell_2023_table,
  format = "html",
  col.names = c("Sickle cell", "Anaemic Count", "Anaemic Percent", "Non Anaemic Count", "Non Anaemic Percent","None value count", "None value Percent")
) %>%
  kableExtra::kable_paper()

# anaemia status and malaria
anaemia_malaria_2023 <- anc_data_processed_subset_2023 %>%
  group_by(anaemia_status, malaria) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  group_by(anaemia_status) %>%
  mutate(percent = count / sum(count) * 100) %>%
  ungroup()
# long
anaemia_malaria_2023_long <- anaemia_malaria_2023  %>%
  pivot_longer(cols = c(count, percent), names_to = "measure", values_to = "value")

malaria_2023_table <- anaemia_malaria_2023_long  %>%
  pivot_wider(names_from = c(anaemia_status, measure), values_from = value)

knitr::kable(
  malaria_2023_table,
  format = "html",
  col.names = c("Malaria", "Anaemic Count", "Anaemic Percent", "Non Anaemic Count", "Non Anaemic Percent","None value count", "None value Percent")
) %>%
  kableExtra::kable_paper()

# Create overall summary table ----
median_age_tab <- anc_data_processed_subset_2023 %>%
  dplyr::summarise(
    var = "median_age",
    median_age = median(age, na.rm = TRUE)
  )
overall_table <- bind_rows(
  age_group_2023_table %>% mutate(Variable = "Age Group"),
  marital_2023_table %>% mutate(Variable = "Marital Status"),
  education_group_2023_table %>% mutate(Variable = "Education Level"),
  profession_group_2023_table %>% mutate(Variable = "Profession"),
  location_2023_table %>% mutate(Variable = "Location"),
  sicklecell_2023_table %>% mutate(Variable = "Sickle Cell"),
)

overall_tab <- bind_cols(
  age_group_2023_table,
  marital_2023_table ,
  education_group_2023_table,
  profession_group_2023_table,
  location_2023_table,
  sicklecell_2023_table
)
print(overall_tab)

knitr::kable(
  overall_tab,
  format = "html",
  col.names = c("variable", "Anaemic Count", "Anaemic Percent", "Non Anaemic Count", "Non Anaemic Percent","None value count", "None value Percent")
) %>%
  kableExtra::kable_paper()


knitr::kable(
  overall_table,
  format = "html",
  col.names = c("variable", "Anaemic Count", "Anaemic Percent", "Non Anaemic Count", "Non Anaemic Percent","None value count", "None value Percent")
) %>%
  kableExtra::kable_paper()

```
### Age structure

```{r age-structure-1, fig.align = "center", fig.height = 6, fig.width = 8}
anc_data_processed_subset_2023 |>
  ggplot(mapping = aes(x = age)) +
  geom_bar(fill = oxthema::get_oxford_colours("sky"), alpha = 0.8) +
  scale_x_continuous(breaks = seq(from = 0, to = 50, by = 5)) +
  scale_y_continuous(breaks = seq(from = 0, to = 20, by = 4)) +
  geom_vline(
    xintercept = 26, 
    colour = oxthema::get_oxford_colours("Oxford blue"),
    linetype = 2
  ) +
  annotate(
    geom = "text", x = 30, y = 14, label = "Median age: 26 years", 
    colour = oxthema::get_oxford_colours("Oxford blue")
  ) +
  labs(
    title = "Age Distribution",
    subtitle = "Age (in years) of women attending ANC in 2023",
    x = "Age (years)",
    y = "Number of women"
  ) +
  oxthema::theme_oxford(grid = "Yy")
```


```{r age-structure-2, fig.align = "center", fig.height = 6, fig.width = 8}
anc_data_processed_subset_2023 |>
  dplyr::count(age_group) |>
  ggplot(mapping = aes(x = age_group, y = n)) +
  geom_col(fill = oxthema::get_oxford_colours("sky"), alpha = 0.8) +
  scale_y_continuous(
    breaks = seq(from = 0, to = 60, by = 10)
  ) +
  labs(
    title = "Age Distribution",
    subtitle = "Age group of women attending ANC in 2023",
    x = "Age group",
    y = "Number of women"
  ) +
  coord_flip() +
  oxthema::theme_oxford(grid = "X")
```

### Distribution of haemoglobin values

```{r hb-histogram, fig.align = "center", fig.width = 8, fig.height = 6}
anc_data_processed_subset_2023 |>
  ggplot(aes(x = haemoglobin)) +
  geom_histogram(fill = oxthema::get_oxford_colours("sky"), alpha = 0.8) +
  labs(
    title = "Haemoglobin values distribution",
    subtitle = "Haemoglobin values of women attending ANC in 2023",
    x = "Hb (g/L)", y = "Number of women"
  ) +
  oxthema::theme_oxford(grid = "Yy")
```

```{r hb-boxplot, fig.align = "center", fig.height = 6, fig.width = 4}
boxplot(
  x = anc_data_processed_subset_2023$haemoglobin,
  border = oxthema::get_oxford_colours("Oxford blue"),
  col = oxthema::get_oxford_colours("sky"),
  lwd = 1.5,
  frame.plot = FALSE,
  main = "Haemoglobin values distribution",
  xlab = NULL, 
  ylab = "Hb (g/L)"
)
```

#2023 BOXPLOT 
```{r boxplot, fig.align = "center", fig.height = 6, fig.width = 4}
boxplot(
  x = anc_data_processed_subset_2023$haemoglobin,
  border = oxthema::get_oxford_colours("Oxford blue"),
  col = oxthema::get_oxford_colours("sky"),
  lwd = 1.5,
  frame.plot = FALSE,
  main = "Haemoglobin values distribution",
  xlab = NULL, 
  ylab = "Hb (g/L)"
)

#boxplot of age and anaemia status in 2023
ggplot(anc_data_processed_subset_2023, aes(x = anaemia_status, y = age, fill = anaemia_status)) +
  geom_boxplot() +
  labs(title = "Comparison of Age by Anaemia Status in 2023", 
       x = "Anaemia Status", y = "Age(year)") +
  scale_fill_manual(values = c("True" = "red", "False" = "blue")) +
  theme_minimal()

#boxplot of haemoglobin and education
ggplot(anc_data_processed_subset_2023, aes(x = education_level_summary, y =haemoglobin , fill = education_level_summary)) +
  geom_boxplot() +
  labs(title = "Comparison of haemoglobin level by education in 2023", 
       x = "education level", y = "haemoglobin level(g/L)") +
  scale_fill_manual(values = c("True" = "red", "False" = "blue")) +
  theme_minimal()+
 theme(axis.text.x = element_text(angle = 45, hjust = 1))

#boxplot of haemoglobin and profession
ggplot(anc_data_processed_subset_2023, aes(x = profession_summary, y =haemoglobin , fill = profession_summary)) +
  geom_boxplot() +
  labs(title = "Comparison of haemoglobin level by profession in 2023", 
       x = "profession group", y = "haemoglobin level(g/L)") +
  scale_fill_manual(values = c("True" = "red", "False" = "blue")) +
  theme_minimal()+
 theme(axis.text.x = element_text(angle = 45, hjust = 1))


#boxplot of haemoglobin and maraital status
ggplot(anc_data_processed_subset_2023, aes(x = marital_status, y =haemoglobin , fill = marital_status)) +
  geom_boxplot() +
  labs(title = "Comparison of haemoglobin level by marital status in 2023", 
       x = "maraital status", y = "haemoglobin level(g/L)") +
  scale_fill_manual(values = c("True" = "red", "False" = "blue")) +
  theme_minimal()


#boxplot of haemoglobin and sickle cell
ggplot(anc_data_processed_subset_2023, aes(x = sickle_cell, y =haemoglobin , fill = sickle_cell)) +
  geom_boxplot() +
  labs(title = "Comparison of haemoglobin level by sickle cell in 2023", 
       x = "sickle cell test result", y = "haemoglobin level(g/L)") +
  scale_fill_manual(values = c("True" = "red", "False" = "blue")) +
  theme_minimal()
#boxplot of haemoglobin and malaria 
ggplot(anc_data_processed_subset_2023, aes(x = malaria, y =haemoglobin , fill = malaria)) +
  geom_boxplot() +
  labs(title = "Comparison of haemoglobin level by malaria in 2023", 
       x = "malaria test", y = "haemoglobin level(g/L)") +
  scale_fill_manual(values = c("True" = "red", "False" = "blue")) +
  theme_minimal()


```


## Outcome variable and bivariate analysis

```{r bivariate-table}
knitr::kable(
  x = anc_data_summary_bivariate_table_2023 |>
    dplyr::select(-var_set),
  col.names = c("", "", "")
) |>
  kableExtra::kable_styling(full_width = FALSE) |>
  kableExtra::pack_rows(
    group_label = "Age",
    start_row = 1, end_row = 1
  ) |>
  kableExtra::pack_rows(
    group_label = "Age Group",
    start_row = 2, end_row = 8
  ) |>
  kableExtra::pack_rows(
    group_label = "Haemoglobin",
    start_row = 9, end_row = 9
  ) |>
  kableExtra::pack_rows(
    group_label = "Profession",
    start_row = 10, end_row = 22
  ) |>
  kableExtra::pack_rows(
    group_label = "Education Level",
    start_row = 23, end_row = 28
  ) |>
  kableExtra::pack_rows(
    group_label = "Marital Status",
    start_row = 29, end_row = 31
  ) |>
  kableExtra::pack_rows(
    group_label = "Location",
    start_row = 32, end_row = 55
  ) |>
  kableExtra::pack_rows(
    group_label = "Sickle Cell",
    start_row = 56, end_row = 58
  ) |>
  kableExtra::pack_rows(
    group_label = "Malaria",
    start_row = 59, end_row = 60
  )
```

### Anaemia status and age

```{r anaemia-status-age-barplot, fig.align = "center", fig.width = 8, fig.height = 6}
anc_data_processed_subset_2023 |>
  dplyr::filter(!is.na(anaemia_status)) |>
  ggplot(mapping = aes(x = age)) +
  geom_bar(fill = oxthema::get_oxford_colours("sky"), alpha = 0.8) +
  scale_x_continuous(breaks = seq(from = 0, to = 50, by = 5)) +
  scale_y_continuous(breaks = seq(from = 0, to = 20, by = 4)) +
  labs(
    title = "Age Distribution by Anaemia Status",
    subtitle = "Women attending ANC in 2023",
    x = "Age (years)",
    y = "Number of women"
  ) +
  facet_wrap(. ~ anaemia_status, ncol = 2) +
  oxthema::theme_oxford(grid = "Yy")
```

```{r anaemia-status-age-group-barplot, fig.align = "center", fig.width = 6, fig.height = 8}
anc_data_processed_subset_2023 |>
  dplyr::filter(!is.na(anaemia_status)) |>
  dplyr::count(anaemia_status, age_group) |>
  ggplot(mapping = aes(x = age_group, y = n)) +
  geom_col(fill = oxthema::get_oxford_colours("sky"), alpha = 0.8) +
  scale_y_continuous(
    breaks = seq(from = 0, to = 40, by = 10)
  ) +
  labs(
    title = "Age Distribution",
    subtitle = "Age group of women attending ANC in 2023",
    x = "Age group",
    y = "Number of women"
  ) +
  coord_flip() +
  facet_wrap(. ~ anaemia_status, nrow = 2) +
  oxthema::theme_oxford(grid = "Xx")
```

```{r anaemia-status-age-violin, fig.align = "center", fig.width = 8, fig.height = 6}
anc_data_processed_subset_2023 |>
  dplyr::filter(!is.na(anaemia_status)) |>
  ggplot(mapping = aes(x = anaemia_status, y = age)) +
  geom_violin(
    fill = oxthema::get_oxford_colours("sky"), alpha = 0.8,
    colour = oxthema::get_oxford_colours("Oxford blue")
  ) + 
  labs(
    title = "Age Distribution by Anaemia Status",
    subtitle = "Women attending ANC in 2023",
    x = "",
    y = "Age (years)"
  ) + 
  oxthema::theme_oxford(grid = "Yy")
```

`


